server.port=8080
spring.datasource.url=jdbc:postgresql://postgre777.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=jungkwan
spring.datasource.password=rjd13038!!!!!
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
azure.eventhub.namespace-host=event-hub-777.servicebus.windows.net
azure.eventhub.name=event-hub-777
azure.eventhub.connection-string=Endpoint=sb://event-hub-777.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=LBpQQTDJYfhIJnDlV/be7RCC3Rkrgcsww+AEhLgu78M=
python.agent.url=http://ai-agent.backend333.com:8000/analyze

