server.port=8080
spring.datasource.url=jdbc:postgresql://YOUR-POSTGRES-DOMAIN.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=YOUR-USERNAME
spring.datasource.password=YOUR-PASSWORD
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
azure.eventhub.namespace-host=YOUR-EVENT-HUB-NAME.servicebus.windows.net
azure.eventhub.name=YOUR-EVENT-HUB-NAME
azure.eventhub.connection-string=Endpoint=sb://YOUR-EVENT-HUB-NAME.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=YOUR-POSTGRES-ACCESS-KEY
python.agent.url=http://YOUR-PYTHON-AGENT-DOMAIN:8000/analyze

